train:
    dreambooth:
        _target_: src.datasets.dreambooth.DreamBoothTrainDataset
        data_path: /Users/danila/Downloads/bears
        placeholder_token: sks
        class_name: dog
        instance_transforms: ${transforms.instance_transforms.train}

val:
    db_liv_small:
      _target_: src.datasets.dreambooth.DreamBoothLivingSmall
      data_path: /Users/danila/Downloads/bears2
      placeholder_token: sks
      class_name: dog
